language: node_js
node_js:
  - 'stable'

services:
  - 'mongodb'
  - 'docker'

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - cd fact-bounty-server/
  - npm install && npm test 